with checks as (
  select 'materialiser function exists' check_name,case when exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='materialize_recurring_duty_assignments' and p.prokind='f' and pg_get_function_identity_arguments(p.oid)='p_horizon_days integer') then 'PASS' else 'FAIL' end result
  union all select 'materialiser security and search path',case when exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='materialize_recurring_duty_assignments' and p.prosecdef and coalesce(array_to_string(p.proconfig,','),'') like '%search_path=public%') then 'PASS' else 'FAIL' end
  union all select 'materialiser execute restricted',case when has_function_privilege('service_role','public.materialize_recurring_duty_assignments(integer)','EXECUTE') and not has_function_privilege('authenticated','public.materialize_recurring_duty_assignments(integer)','EXECUTE') and not has_function_privilege('anon','public.materialize_recurring_duty_assignments(integer)','EXECUTE') then 'PASS' else 'FAIL' end
  union all select 'outcome uniqueness and schema',case when exists(select 1 from pg_constraint c join pg_class r on r.oid=c.conrelid join pg_namespace n on n.oid=r.relnamespace where n.nspname='public' and r.relname='recurring_occurrence_outcomes' and c.conname='recurring_occurrence_outcomes_one_per_rule_date') then 'PASS' else 'FAIL' end
  union all select 'active register uniqueness',case when to_regclass('public.recurring_rules_one_active_register_per_member_slot_idx') is not null then 'PASS' else 'FAIL' end
  union all select 'shared lifecycle lock present',case when exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='materialize_recurring_duty_assignments' and pg_get_functiondef(p.oid) like '%ajpa-stage2c-lifecycle%') then 'PASS' else 'FAIL' end
  union all select 'cron command uses 142',case when to_regclass('cron.job') is null or (select count(*) from cron.job where jobname='ajpa-recurring-assignment-materialiser-daily' and active and schedule='17 14 * * *' and command like '%materialize_recurring_duty_assignments(142)%')=1 then 'PASS' else 'FAIL' end
)
select check_name,result from checks order by check_name;
