-- Stage 3B read-only verification.
with checks as (
  select 'request idempotency table exists' as check_name, case when to_regclass('public.recurring_registration_requests') is not null then 'PASS' else 'FAIL' end as result
  union all select 'request id uniqueness exists', case when exists (select 1 from pg_constraint c join pg_class r on r.oid=c.conrelid join pg_namespace n on n.oid=r.relnamespace where n.nspname='public' and r.relname='recurring_registration_requests' and c.contype='p') then 'PASS' else 'FAIL' end
  union all select 'Stage 3B recurring registration RPC exists', case when exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='apply_recurring_registration' and p.prokind='f' and pg_get_function_identity_arguments(p.oid)='p_slot_id uuid, p_start_date date, p_scope text, p_count_n integer, p_until_date date, p_request_id uuid') then 'PASS' else 'FAIL' end
  union all select 'Stage 3B RPC is SECURITY DEFINER with safe search_path', case when exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='apply_recurring_registration' and p.prosecdef and coalesce(array_to_string(p.proconfig,','),'') like '%search_path=public%') then 'PASS' else 'FAIL' end
  union all select 'authenticated execute is granted and anonymous execute is revoked', case when has_function_privilege('authenticated','public.apply_recurring_registration(uuid,date,text,integer,date,uuid)','EXECUTE') and not has_function_privilege('anon','public.apply_recurring_registration(uuid,date,text,integer,date,uuid)','EXECUTE') then 'PASS' else 'FAIL' end
  union all select 'outcome uniqueness remains enforced', case when exists (select 1 from pg_constraint where conname='recurring_occurrence_outcomes_one_per_rule_date') then 'PASS' else 'FAIL' end
  union all select 'active REGISTER uniqueness remains enforced', case when exists (select 1 from pg_indexes where schemaname='public' and indexname='recurring_rules_one_active_register_per_member_slot_idx') then 'PASS' else 'FAIL' end
  union all select 'outcome table direct authenticated writes remain revoked', case when not has_table_privilege('authenticated','public.recurring_occurrence_outcomes','INSERT') and not has_table_privilege('authenticated','public.recurring_occurrence_outcomes','UPDATE') then 'PASS' else 'FAIL' end
  union all select 'request table foreign keys and RLS are present', case when (select count(*) from pg_constraint c join pg_class r on r.oid=c.conrelid join pg_namespace n on n.oid=r.relnamespace where n.nspname='public' and r.relname='recurring_registration_requests' and c.contype='f')=3 and exists (select 1 from pg_class r join pg_namespace n on n.oid=r.relnamespace where n.nspname='public' and r.relname='recurring_registration_requests' and r.relrowsecurity) then 'PASS' else 'FAIL' end
  union all select 'request table direct authenticated access is revoked', case when not has_table_privilege('authenticated','public.recurring_registration_requests','SELECT') and not has_table_privilege('authenticated','public.recurring_registration_requests','INSERT') then 'PASS' else 'FAIL' end
  union all select 'BOOKED outcome source integrity remains enforced', case when exists (select 1 from pg_constraint c join pg_class r on r.oid=c.conrelid join pg_namespace n on n.oid=r.relnamespace where n.nspname='public' and r.relname='recurring_occurrence_outcomes' and c.conname='recurring_occurrence_outcomes_booking_source_check') then 'PASS' else 'FAIL' end
  union all select 'Stage 3A outcome categories remain available', case when exists (select 1 from pg_enum e join pg_type t on t.oid=e.enumtypid join pg_namespace n on n.oid=t.typnamespace where n.nspname='public' and t.typname='recurring_occurrence_outcome' and e.enumlabel in ('DESK_CLOSED','MEMBER_INELIGIBLE','OTHER_UNAVAILABLE')) then 'PASS' else 'FAIL' end
  union all select 'calendar occurrence helper remains available', case when exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='scheduled_duty_slot_occurrence_dates' and p.prokind='f') then 'PASS' else 'FAIL' end
)
select check_name, result from checks order by check_name;
